clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_69_0
  CMAKE_GENERATOR: Visual Studio 15 2017
  PLATFORM_TOOLSET: v141_xp

cache:
  - .ci/boost.cached -> .ci/appveyor_build_boost.bat
  - C:\Libraries\boost_1_69_0\stage -> appveyor_build_boost.bat
  - C:\Libraries\boost_1_69_0\stage_x64 -> appveyor_build_boost.bat

init:
  - git --version
  - git config --global core.autocrlf true

install:
  - git clone -q --depth=1 --branch=master https://github.com/rime/weasel.git weasel\
  - copy /y .ci\build.bat weasel\
  - cd weasel
  - .\appveyor.install.bat

build_script:
  - if "%APPVEYOR_REPO_TAG%" == "false" set WEASEL_BUILD=%APPVEYOR_BUILD_NUMBER%
  - .\build.bat data hant installer
  - cd C:\projects\rime-cantonese

artifacts:
  - path: \weasel\output\archives\weasel-*-installer.exe
    name: Weasel

deploy:
  provider: GitHub
  auth_token:
    secure: kNbaFjiXqhC4z/x80jWG8KOoDedhLlFkOa1V87h82JJsPwD1zwDlnyJfC/whcpgp
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true
