#!/usr/bin/env python3
# -*- coding: utf-8 -*-

with open('jyut6ping3.dict.yaml') as f, open('jyut6ping3_unspaced.dict.yaml', 'w') as g:
    # Header
    for line in f:
        if line == '...\n':
            g.write(line)
            break
        else:
            # Override several configurations
            if line == '# encoding: utf-8\n':
                g.write(line)
                g.write('#\n# NOTICE: This file is auto-generated for reverse lookup.\n')
                g.write('# Do not edit this file directly!\n')
                g.write('# You should edit jyut6ping3.dict.yaml.\n')
            elif line == 'name: jyut6ping3\n':
                g.write('name: jyut6ping3_unspaced\n')
            elif line in \
                [ 'use_preset_vocabulary: true\n'
                , 'import_tables:\n'
                ] or line.startswith('  - '):
                pass
            else:
                g.write(line)

    # Dictionary
    for line in f:
        if line.startswith('#'):
            g.write(line)
        else:
            g.write(line.replace(' ', '='))
