name: Build packages

on:
  workflow_call:

jobs:
  mac:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        export SQUIRREL_VERSION=$(git ls-remote --tags --refs --sort="v:refname" https://github.com/rime/squirrel.git | grep -v '/latest$' | tail -n1 | sed 's/.*\///')
        chmod u+x ./.ci/*
        ./.ci/package-mac.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mac
        if-no-files-found: error
        path: ./output/Squirrel-*.pkg

  windows:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      shell: bash
      run: |
        export WEASEL_VERSION=$(git ls-remote --tags --refs --sort="v:refname" https://github.com/rime/weasel.git | grep -v '/latest$' | tail -n1 | sed 's/.*\///')
        wget https://raw.githubusercontent.com/rime/weasel/refs/tags/${WEASEL_VERSION}/install_nsis.bat
        ./install_nsis.bat
        chmod u+x ./.ci/*
        ./.ci/package-windows.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows
        if-no-files-found: error
        path: ./output/archives/weasel-*.exe
