name: build_packages
on:
  push:
    branch:
      - "main"
    tags:
      - "**"

jobs:
  mac_linux:
    runs-on: ubuntu-latest
    if: ${{ github.ref || github.ref == 'refs/heads/main' }}
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - run: export SQUIRREL_VERSION=$( git ls-remote --tags --refs --sort="v:refname" https://github.com/rime/squirrel.git | tail -n1 | sed 's/.*\///' )
    - run: export SQUIRREL_LINK=https://github.com/rime/squirrel/releases/download/${SQUIRREL_VERSION}/Squirrel-${SQUIRREL_VERSION}.zip
    - run: export SQUIRREL_PACKAGES="cantonese emoji CanCLID/rime-loengfan custom:set:config=default,key=installed_from,value=rime-cantonese custom:clear_schema_list custom:add:schema=jyut6ping3 custom:add:schema=cangjie5 custom:add:schema=stroke custom:add:schema=luna_pinyin lotem/rime-octagram-data lotem/rime-octagram-data@hant lotem/rime-octagram-data:customize:schema=jyut6ping3,model=hant"
    - run: export IBUS_PACKAGES=${SQUIRREL_PACKAGES}
    - run: mkdir output
    - run: chmod u+x .ci/*
    - run: .ci/build_linux.sh
    - uses: softprops/action-gh-release@v0.1.15
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPOSITORY: "${{ github.repository }}"
      with:
        files: output/*
      if: startsWith(github.ref, 'refs/tags/')
    - run: ls output

  windows:
    runs-on: ubuntu-latest
    if: ${{ github.ref || github.ref == 'refs/heads/main' }}
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - run: export WEASEL_VERSION=$( git ls-remote --tags --refs --sort="v:refname" https://github.com/rime/weasel.git | tail -n1 | sed 's/.*\///' )
    - run: export WEASEL_LINK=https://github.com/rime/weasel/releases/download/${WEASEL_VERSION}/weasel-${WEASEL_VERSION}.0-installer.exe
    - run: export WEASEL_PACKAGES="cantonese emoji CanCLID/rime-loengfan custom:set:config=default,key=installed_from,value=rime-cantonese custom:clear_schema_list custom:add:schema=jyut6ping3 custom:add:schema=cangjie5 custom:add:schema=stroke custom:add:schema=luna_pinyin lotem/rime-octagram-data lotem/rime-octagram-data@hant lotem/rime-octagram-data:customize:schema=jyut6ping3,model=hant"
    - run: export SFXHEADER=7zSD.sfx
    - run: sudo apt-get install p7zip-full
    - run: mkdir output
    - run: chmod u+x .ci/*
    - run: i.ci/build_windows.sh
    - uses: softprops/action-gh-release@v0.1.15
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPOSITORY: "${{ github.repository }}"
      with:
        files: output/*
      if: "${{ github.event_name == 'push' && ${{ github.ref }} }}"
    - run: ls output
      if: "${{ success() }}"
